import { type TaskType, TaskPriority, TaskState } from '@/lib/types';

export const mockTasks: TaskType[] = [
  {
    id: '1',
    client: 'Cliente 1',
    description: 'Tarea 1',
    subtasks: [],
    owner: 'Owner 1',
    state: TaskState.THIS_WEEK,
    timeout: 10,
    createdAt: '2023-01-01',
    updatedAt: '2023-01-01',
    priority: TaskPriority.LOW,
  },
  {
    id: '2',
    client: 'Cliente 2',
    description: 'Tarea 2',
    subtasks: [],
    owner: 'Owner 2',
    state: TaskState.THIS_WEEK,
    timeout: 10,
    createdAt: '2023-01-01',
    updatedAt: '2023-01-01',
    priority: TaskPriority.LOW,
  },
  {
    id: '3',
    client: 'Cliente 3',
    description: 'Tarea 3',
    subtasks: ['Subtarea 1', 'Subtarea 2'],
    owner: 'Owner 3',
    state: TaskState.DONE,
    timeout: 10,
    createdAt: '2023-01-01',
    updatedAt: '2023-01-01',
    priority: TaskPriority.LOW,
  },
  {
    id: '4',
    client: 'Cliente 4',
    description: 'Tarea 4',
    subtasks: ['Subtarea 1', 'Subtarea 2'],
    owner: 'Owner 4',
    state: TaskState.TODAY,
    timeout: 10,
    createdAt: '2023-01-01',
    updatedAt: '2023-01-01',
    priority: TaskPriority.LOW,
  },
  {
    id: '5',
    client: 'Cliente 5',
    description: 'Tarea 5',
    subtasks: ['Subtarea 1', 'Subtarea 2'],
    owner: 'Owner 5',
    state: TaskState.BACKLOG,
    timeout: 10,
    createdAt: '2023-01-01',
    updatedAt: '2023-01-01',
    priority: TaskPriority.LOW,
  },
];